repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
  - repo: https://github.com/GitGuardian/ggshield
    rev: v1.35.0 # Use the latest stable ggshield version
    hooks:
      - id: ggshield
        rev: v1.49.0
        language_version: python3
